/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'yongjunjung' at '16. 1. 8 오후 6:05' with Gradle 2.7
 *
 * @author yongjunjung, @date 16. 1. 8 오후 6:05
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
